# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Python requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
